### ISSUE TITLE
Smart Contract - Metatask

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1018]
- [x] identity registration contract #3
  - [x] identity registration contract tests #4
  - [x] identity registration sc for each identity to have stable topup address #5
  - [x] identity registartion fee #6
  - [ ] identity registration stake #7
- [x] identity sc implementation #8
  - [x] identity sc tests #9
- [ ] payment schema documentation #10
- [x] initial DEX to enable topups with ETH #11
  - [x] DEX upgradability pattern (proxy) #12
  - [x] DEX tests #13
- [ ] token recovery plugin for airdrop retrieval #14
- [ ] identity registrator rewarding #15

**Comment by chompomonim** [comment]
@zolia please close this old and already finished task.
