### ISSUE TITLE
Leaderboard for new bounty rules (based on MYSTT calculations)

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1312]
- [ ] Show nodes position # in Leaderboard. Nodes position should be calculated based on MYSTT earnings during that month.
- [ ] Two leaderboards:
     - For residential nodes (in US, UK, IT, DE, NL, AU), 250 of them will be getting paid.  --> max 50 USD, based on MYST
     - Global any nodes grouped by countries. First 3 nodes in any country should get paid. --> max 10 USD, based on MYSTT
- [ ] Update payout API to do payouts according to leaderboard data and new payment rules.
- [ ] Group payout by wallets. So we could reduce the amount of transactions.
- [ ] In MMN show users total MYSTT collected? And USD planned to be in the payout.
- [ ] Reset MYSTT balance in DB only for nodes which been paid.
- [ ] Remove availability from the equation
- [ ] In MMN change data in "Availability" box to show current Leaderboard position, tokens earned ... 
- [ ] Add graphs for earning per day.
- [ ] The last 10 sessions table should show earning per session.

**Comment by chompomonim** [comment]
all tasks moved into #milestone/33
