### ISSUE TITLE
Payment system rollout into testnet - METATASK

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1372]
Following tasks should be finished before payments goes into testnet:

* [x] Run couple provider nodes with internal alpha payment support. [@zolia]
* [x] Redeploy into Goerli testnet and change all the configs. [@chompomonim @vkuznecovas]
* [x] Visibility to grafana dashboard for payment data [@chompomonim @zolia]
* [ ] Debug accountant penalty math (make sure that accountant is not blocking) (https://github.com/mysteriumnetwork/accountant/issues/44)
* [x] Handle ethereum client timeouts (#1458)
* [ ] Add base auth for `/data` list endpoints (https://github.com/mysteriumnetwork/accountant/issues/45)
* [x] Setup Transactor monitoring (https://github.com/mysteriumnetwork/transactor/issues/15)
* [x] Payment disablement flag (#1459)
* [x] Change transactor topup logic. (https://github.com/mysteriumnetwork/transactor/issues/28)
* [x] Reduce unattended upgrade to 1 hour. 
* [x] Ensure backwards compatibility [@zolia @vkuznecovas]
* [x] Test released alpha payments internally and manually. [all]
* [x] Stress test for Accountant (with noop consumers) [@zolia]
* [x] Release payments and start node upgrade rollout

Mobile:
* [ ] Push notification to inform that user have to topup (if consumer balance less then 0.01 MYSTT) #1457

SuperProxy:
* [ ] Deploy new version of node consumer (https://github.com/mysteriumnetwork/supernode/issues/183)
* [ ] Register SuperProxy identities in Registry (https://github.com/mysteriumnetwork/supernode/issues/183)
* [ ] Mint a lot of tokens for SuperProxy identities (https://github.com/mysteriumnetwork/supernode/issues/183)
* [ ] Run bot which ensure 1 session per day with all accessible providers (https://github.com/mysteriumnetwork/supernode/issues/183)

MMN:
* [x] Show consumer "points" (balances) in MMN. [Ignas]

After release:
* [x] Provider settlement E2E tests for node [@vkuznecovas]
* [x] Start modelling possible payment / payout models for current node runners based on test myst tokens earned.
* [ ] P2P payment models based on UK  - presentation @Ieva

================ DONE DURING SECOND ITERATION ================
* [x] Add transactor fee config into deployment environments.
* [x] Use stake for any identity registration (consumers and providers).
* [x] Recheck and fix infra deployment
* [x] Transactor should have settleAndRebalance endpoint(https://github.com/mysteriumnetwork/transactor/issues/24)
* [x] Implement promise settlement in provider node (settle when 90% of balance is used)
* [x] Implement balance endpoint on Accountant and expose through node TequilAPI
* [x] Mobile app fixes (#800) :
    * [x] Add register and faucet buttons into mobile app
    * [x] Implement identity register, faucet button and balance endpoint native bindings
* [x] Setup Accountant monitoring. (https://github.com/mysteriumnetwork/accountant/issues/40)
* [x] We have got 1000 GETH for beginning.

================ DONE DURING FIRST ITERATION ================
* [x] Add `settleAndRebalance` function into Smart contracts and deploy smart contracts into Kovan and update all the related things.  (https://github.com/mysteriumnetwork/payments-smart-contracts/issues/75)

* [x] Delpoy all the infra
   - [x] Register accountant on newest Registry in Kovan
   - [x] Update smart contract addresses on Accountant and Transactor services #...
   - [x] Topup MYSTT and KETH for Transactor and Accountant

* [x] Transactor should have register identity call which should have stake as parameter (https://github.com/mysteriumnetwork/transactor/issues/17)
* [x] Transactor during consumer and provider registration should auto top-up C channels (https://github.com/mysteriumnetwork/transactor/issues/18)
* [x] Set fee for Transactor through params and return it through endpoint (https://github.com/mysteriumnetwork/transactor/issues/19)

* [x] Node should learn how to register consumer identity #1377 
    * [x] adapt tequilapi endpoint to register identity
    * [x] register identity through CLI

* [x] On service start, we should check if the provider is registered as a provider, if not - we should register the provider #1385

* [x] Provider should reject not registered consumer from session establishment (disabled by default ) #1373 
* [x] Remove auto top up after registration from node #1381

* [x] Add faucet call through CLI #1378

* [x] Accountant should settle his (consumer issued) promises when there is 100 MYSTT with 1.23 gwei gas price

* [x] Node, fix bugs: #1387

**NOTE:** Ensure all the default configs:
   - ~~node: 1 minute price is 0.00100000 MYST #1380~~
   - transactor: faucet period 1 week and amount 125 MYSTT (only for C channels)
   - registration auto top-up for provider: 1250 MYSTT
   - default transactor fee = 1 MYSTT

**Comment by chompomonim** [comment]
AccountantID: 0x45922e4459131141173F5a6ED09A5AdCd5bA17da
Accountant operator: 0xfb9cbd471f27e69f9ca94c7e804601a1f87d0569

**Comment by chompomonim** [comment]
**AFTER ALPHA RELEASE**
 * [ ] Promotion flow tasks [will be done after alpha release]
   - Give tokens during promotion from Consumer to Provider.
   - Transactor endpoint for provider channel stake increase.
   - Node should have `increase_stake` functionality.
- Set gas price for Transactor and Accountant (via params?)

**Comment by chompomonim** [comment]
Payments are on testnet, so closing this issue.
