### ISSUE TITLE
Node diagnostics UI

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#1386]
Node provider should be able quickly check it's status with common diagnostics and sessions statuses in local UI.

**General information:**
-  Identity unlocked
-  Registered to MMN (Need to discuss if this is is optional)
-  Tequilapi started
-  UI server started (This one may not be needed as user will not be able to see UI if this is not working)

**Service information:**
-  Registered proposal to discovery
-  OpenVPN started (or Wireguard, or both, depending on proposal)
-  Whitelist enabled (Need to discuss if this is is optional)
-  UPnP enabled
-  NAT punched
-  Message broken connected (This is to tell if provider can connect to NATS server)

**Sessions information:**
-  Session counter and ID
-  Dialog created
-  Session created
-  Connection established (This means that consumer is connected and IP is changed. Need to discuss about noop service)
-  Data send
-  Data received

![diagnostics_modal](https://user-images.githubusercontent.com/13434315/68108988-1aff7200-fef2-11e9-80ab-9cdb50ed7a93.png)
![diagnostics](https://user-images.githubusercontent.com/13434315/68108994-218de980-fef2-11e9-9d12-045a2114f9df.png)

 - [ ] Store events locally (last xx events in memory) https://github.com/mysteriumnetwork/node/issues/1395
 - [ ] Local web-ui to present local state https://github.com/mysteriumnetwork/node/issues/1396
 - [ ] Export local state as json for mmn https://github.com/mysteriumnetwork/node/issues/1397
 - [ ] Tequilapi api endpoint https://github.com/mysteriumnetwork/node/issues/1398

**Comment by chompomonim** [comment]
I suppose by 'local UI' you mean our WebUI?

**Comment by etherunit** [comment]
[node_diagnostics.pdf](https://github.com/mysteriumnetwork/node/files/4256253/node_diagnostics.pdf)

**Comment by chompomonim** [comment]
This is similar to #2452 and we're going to work on it instead.
