### ISSUE TITLE
Hot fixes for WebUI

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1692]
Here is a list of all hotfixes needed to be done for current WebUI.

* [ ] Values not matching between my Dashboard and Network Bounty Leaderboard #1624 
* [ ] Add information about token earning into WebUI #1571 
* [ ] Add notification "Please restart service after changing settings in webUI" #1701
* [ ] WEB-UI show attempts to update NAT status on public IP #1696

**Comment by tadaskay** [comment]
You can use the milestones

**Comment by chompomonim** [comment]
Created milestone for [hot fixes in WebUI](https://github.com/mysteriumnetwork/node/milestone/31)
