### ISSUE TITLE
Create a desktop app

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1734]
In the initial version, we're aiming to have at least MacOSX support and documentation so people would have good reference implementation on how to build on top of Mysterium Network. 

Tasks to do before release:
- [x] initial version (with connect functionality)
- [x] proposal refresh
- [x] indicate active proposal
- [x] proposal search/filter #1871
- [x] proposal country collaped by default
- [x] show active session stats #1873
- [x] ID registration status in splash screen
- [x] account management and topups #1880
- [x] eslint/code cleanup
- [x] tequilapi consumer state
- [x] mysterium-vpn-js cleanup
- [x] mysterium-vpn-js licensing
- [ ] app install configs (update-resolv-conf, etc.) config-dir runtime-dir
- [ ] CI
- [x] supervisor repair
