### ISSUE TITLE
Providers should be able to change price

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1962]
- [x] Possibility for the provider to set his own price for any proposal (free is also acceptable). This should be set per service and stored locally. 
- [x] Allow for a consumer to change the price range (configurable on the fly and stored in config file). The default max price should be 0.001 per minute and 0.5 per GB.
- [x] Expose setting price via tequila and CLI.
- [x] Expose setting price via WebUI (in UI don't allow to set a higher price than max price).
