### ISSUE TITLE
Fast identity registration

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2027]
Registration check should be changed into a promise exchange (if acc exchanges promise, then it’s a good consumer). 

As a part of this epic transactor should notify accountant when the user already asked for registration, and an accountant can wait till the transaction will be mined while in same time he can act as an identity would be already registered on-chain. If after some time identity is still not registered, accountant could try sending tx into blockchain by himself.

**Comment by chompomonim** [comment]
Tasks needed to implement this.

**Transactor**
- [ ] Transactor should expose state of not mined registrations.

**Hermes**
- [ ] When new promise exchange comes, hermes:
   - checks if he has already channel data with this consumer
   - if not checks blockchain channel status
   - if not then calls transactor to get info about not mined registration and bounty given.
   - if transactor gave 0 bounty, then check channel balance on the blockchain. 

**node**
- [ ] The provider should skip checking consumer's registration on blockchain and simply try to exchange the first promise. 
- [ ] Consumer should be able to initialize connection after transactor agreed to register him.
