### ISSUE TITLE
Manual and configurable auto settlement

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2263]
- [x] Transactor calls(done way back when)
- [x] CLI to settle manually(done, but updated with #2281)
- [x] CLI to set auto settlement thresholds(already configurable via config or passed in as flags)
- [x] Visualise how much accountant will take during settlement (cli + tequila) (#2281)
- [x] Store history of settlements (#2287)
