### ISSUE TITLE
Get ready for network fork

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2401]
After smart contract updates, we're planning to do network fork. For that, we need additional Hermes and Transactor.

- [x] Deploy latest version of smart contracts into Goerli #2503
- [x] Launchpad devnet repo build from v3 branch #2506
- [x] Build relevant v3 branches in docker hub #2507
- [x] Deploy services on devnet:
    - [x] [devnet] Deploy Prometheus #2508
    - [x] [devnet] Deploy Grafana #2509
    - [x] [devnet] Deploy Discovery #2510
    - [x] [devnet] Deploy Hermes #2511
    - [x] [devnet] Deploy Transactor #2512
    - [x] [devnet] Deploy Quality #2513
    - [x] [devnet] Deploy Location #2514
    - [x] [devnet] Deploy Broker #2515
    - [x] [devnet] Deploy Trust #2516
    - [x] [devnet] Deploy Monitoring #2517
    - [x] [devnet] Deploy mmn #2520
- [x] Adapt desktop apps to use v3 node #2518
- [x] Adapt android app to use v3 node #2519
- [x] Build devnet Android app(.apk) for testing #2521
- [x] Build devnet Desktop apps(.dmg,.exe) for testing #2522
- [x] Adapt quality oracle to changes in payments #2540
