### ISSUE TITLE
Tequilapi logout endpoint

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2658]
- [x] Introduce logout endpoint, which clears auth session #2671
- [x] Possibility to check if node still has default password set (logging in is inconvenient) #2672, https://github.com/mysteriumnetwork/mysterium-vpn-js/pull/57
- [ ] Drop username/password concept and leave just password login
- [x] Possibility to reset password then user forgot it (via CLI command) #2704
