### ISSUE TITLE
Registration with referral codes for providers

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2678]
We should adapt referral codes so providers could register their identity and get some stake (set in referral code). 

**Transactor:**

- [x]  Expose reward amount for given referral code
- [x]  Check registration stake so that: 
    - req.stake <= referral token reward
    - referral token reward >= stake goal (minimal stake)
    - if req.stake < referral token reward
       referral token reward = req.stake

**Node:** (#2715)
- [x] Change registration flow with referral token for provider(backend):
    1) Fetch token reward from transactor
    1) Set stake to token reward
    1) Register with token
- [x] Make all needed changes for tequila api
- [x] Add support for registration with referral codes in CLI

**WebUI:**
- [x] Add referral code field in on-boarding
- [x] Delete "set stake" features from on-boarding when registering with  referral code

**Misc:** 
1) Generate a bunch of referral tokens for the providers in the special list

**Marketing:**
1) Figure out a way to contact providers in the special list and send them referral tokens
