### ISSUE TITLE
User friendly CLI

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2837]
For our advanced linux and macOS users we could create easy to use CLI client for consumers.

**Add additional commands for `myst` tool:**
- [x] `myst account register`:  It should create identity, unlock it and show topup address where to topup (if not testnet). If user is running it second time, check if there is identity and don't allow create second one.  (https://github.com/mysteriumnetwork/node/pull/2854 / https://github.com/mysteriumnetwork/node/pull/2867)
- [x] `myst account info` if not registered, suggests to register. Should also show balance of default identity ( https://github.com/mysteriumnetwork/node/pull/2867 )
- [x] `myst account topup [amount of tokens] --currency=BTC`: shows topup instructions and address where to send tokens. ( https://github.com/mysteriumnetwork/node/pull/2867 )
- [x] `myst connection up [node identity]`:  connects into node. Should show message that identity is not registered (or balance is empty). Could do `myst register` automatically in background while in testnet.  ( https://github.com/mysteriumnetwork/node/pull/2862 )
- [x] `myst connection down`:  disconnect from node ( https://github.com/mysteriumnetwork/node/pull/2862 )
- [x] ~~`myst proposals [--all]`:  lists all proposals with additional info (country, IP type, price) (only wireguard if without `--all`)~~
- [x] `myst connection proposals --country=[country] --ip_type=[ip_type]`: list filtered proposals (https://github.com/mysteriumnetwork/node/pull/2859)
- [x] `myst connection info`: shows connection status. ( https://github.com/mysteriumnetwork/node/pull/2865 )
- [x] Make possible to set which identity is default (could be only in advances interactive CLI). ( https://github.com/mysteriumnetwork/node/pull/2870 )
- [x] Update `myst help` command. (This is sort of auto updated as it's being built)
- [x] Don't show terminal logs for interactive commands.  ( https://github.com/mysteriumnetwork/node/pull/2853 )
- [x] Show Terms of Use once, ask to agree and don't show anymore when agreed. ( https://github.com/mysteriumnetwork/node/pull/2894 stuck in review )
- [x] Update CLI documentation in docs-v2 after that. ( https://github.com/mysteriumnetwork/documentation/pull/15 )

On the side:

- have auto un-lock for `connect` type commands.  ( https://github.com/mysteriumnetwork/node/pull/2920 )
- dont require the `0` if no stake is provided in register command  ( https://github.com/mysteriumnetwork/node/pull/2869 )
