### ISSUE TITLE
Consumers should be able to create referral codes

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2886]
dVPN app consumers should be able to generate referral code out of their app user interface (mobile, desktop, cli) and share it its friends.

Code can be used up to 3 times and will topup up to 10MYSTT for its user and same amount to referee.

- [x] transactor should expose API for consumer app to generate one such unique code
- [ ] desktop app should have "share and earn" view in settings menu
- [ ] mobile app should have "share and earn" view in menu
- [x] cli should have possibility to generate referral code to share 

In addition to code itself, UIs should show how many times code was used.

**Comment by vkuznecovas** [comment]
Transactor already exposes such an endpoint.

**Comment by vkuznecovas** [comment]
Cli already exposes such a command `identities referralcode <identity>`

**Comment by chompomonim** [comment]
UI related tasks moved into #2960 and #2961.
