### ISSUE TITLE
Grafana tracking users improvement

### ISSUE THREAD

**Issue by eugenegoncharuk** [mysteriumnetwork/node#3335]
For marketing, there is a need for in-depth information about the users.

Need to introduce a **Cohort analysis** under the [Grafana](https://testnet2-grafana.mysterium.network/d/CTmJkpPGk/okrs-users?orgId=1) (what is happening with the same set of users over 3 months) :
 - [ ] How many stay?
 - [ ] How many do we lose?
 - [ ] How do we track retention? Are people staying with us and for how long? 
 - [ ] What is a user lifetime value measured in days spent in the network?
 
Abbreviations:
[**New**] **Acquired** user definition: Acquisition:
- User should be acquired during the quarter (ID created) 
- Users should try to have at least one successful connection (10 Mb) during the quarter 

**Monthly** **Active** user definition: Product 
- 1 session in the last month
- Had at least 30 minutes of session time (many sessions)/ quarter
- User should be active for more than 2 days in the last 3 months

**Comment by creotiv** [comment]
can we use GA or similar for this?
