### ISSUE TITLE
Tequilapi. Add endpoints for service management

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#339]
Acceptence criteria:
- Tequilapi `create service` endpoint must start VPN server
- Tequilapi endpoints returns status DTO after starting VPN server
- `myst service` subcommand starts servise thru Tequilapi
- CLI demo subcommand `service start` starts service thru Tequilapi

Tasks:
- [x] Refactor CLI flag bootstraping #329
- [x] Convert Service.Manager from CLI command to Service #730
- [x] Move `myst service` subcommand to Tequilapi endpoint `POST /service` #731
- [x] Tequilapi endpoints `POST /service` returns status DTO #732
- [x] CLI demo subcommand `service start` starts service thru Tequilapi #733

**Comment by Waldz** [comment]
@soffokl can You create subtasks to show progress there You are
