### ISSUE TITLE
Allow manual bounty claming

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3420]
After initial bounty payout refactoring will be done (#3417 #3418 #319), we may start implementing more advanced payout features which will give users much more flexible payout options (e.g. weekly bounty payouts, manual claiming, choosing between Ethereum and Polygon).

- [ ] There should be automated action which on fist day of month would generate merkle root and send it to blockchain (using `Rewarder` smart contract). 
- [ ] Users should be able to choose blockchain where to get payouts (ideally in MMN interface).
- [ ] NodeUI should visualise blockchain in addition to chosen beneficiary address.
- [ ] MMN should show Claim button for users, so they could claim earned payouts at any time they like (e.g. once in couple of moths or each week).
- [ ] Merkle root generation should be done automatically (once in a week) -->bounty program will be changed from monthly to weekly
- [ ] Autodetect potential cheating (e.g. all sessions from same country as exit ip, or identity is paying to himself...)

**Comment by Donatas-MN** [comment]
Not relevant anymore as most of suggestions will be covered by MainNet updates.
