### ISSUE TITLE
Improve docker configuration

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3681]
Problem
======

After recent improvements in docker configuration we started using port restricted cone nat. This simplified docker configuration (don't need manual port forwarding in most of cases) but another problem appeared. Now clients which ISP is using symmetric NAT can't connect to such nodes, so users from some mobile operators can't connect to 55% of our nodes. 

Solution
=====

- [x] Research docker setup, maybe there are potential solutions.
- [x] Recommend for users (in NodeUI) to manually configure ports (when this is relevant) #3688
- [x] Allow users to choose between manual and auto port configuration in Windows installer #3689
- [x] Extend quality oracle and discovery so it could mark and filter out nodes which has "port restricted cone nat" #3710
- [x] Add detection in node if consumer ISP is using symmetric NAT, it such case consumer app should filter out unaccessible nodes. Also user should be able to enable/disable in config such auto detection. #3709

**Comment by chompomonim** [comment]
@Snawoot recently proposed alternative solution - using VirtualBox instead of docker on Windows.

_"To solve Docker NAT problem instead of running docker on windows there is a more direct approach which grants same network connectivity as running RaspberryPi in same network. 

VirtualBox has an option to run VMs in background and has a one-click import of Virtual Appliances in a well-known OVA format this appliance can be configured to connect to network in bridged mode, therefore there will be no additional symmetric NAT imposed by virtualization networking

I'm running node to test it. It's running inside VM with Alpine Linux (total image size less than 100 MB) which is running on Windows which is running in VM on my Linux desktop.

Another interesting property of such network configuration: I can use Mysterium VPN as a Consumer on Windows while same system is running bridged VM with Provider node. Both do not affect each other.
"_

We already tested this using android app on problematic ISP network and there are no issues with connectivity found.

**Resource usage:**
CPU - almost on par with native if HW virtualisation is enabled.
RAM - somewhere near 512 MB 
HDD - initially about hundreds of megabytes, will grow as logs grow. VMDK images usually use sparse files
Speed - needs investigation. While running on two levels of virtualisation (Linux on Windows on Linux) we see bad speed with fast.com. It may be problem on double virtualisation or there is need for some additional networking setup.

**Comment by soffokl** [comment]
VirtualBox solves the problem only partly. We still will need to resolve all the tasks listed to improve the connectivity rate, since routers can cause the same problem with a port restricted cone NAT that we have with a docker, and we need to filter these nodes to supported consumers only. 

There are also some limitations for bridging Wifi adapters in VirtualBox when they could not work at some systems:
> Bridged may not always work with a Wifi adapter, due to strict implementation of the Wifi protocols by either the wifi adapter driver or the access point firmware. Technically Wifi cannot Bridge, but some combinations of wifi adapter drivers and access point firmware implement these protocols in a lax fashion so Bridged can squeeze through

It's good to have both Docker image and VirtualBox appliance, but this is a different issue.
