### ISSUE TITLE
Conform to godoc

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#399]
We're pretty close to conforming to godoc but not there yet.

Things that need doing:
- [ ] Add missing package comments
- [ ] Add examples where appropriate
- [ ] Add godoc to readme
