### ISSUE TITLE
Basic Wireguard support for Providers

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#487]
As a node developer
In order to start developing / testing wireguard service consumer
I want to be able to run some basic Wireguard service

- [x] Kernel based wireguard support for Linux #389
- [x] Adapt statistics module for WG #489
- [x] Adapt cli client to support WG
- [x] Package WG ubuntu / debian / centos packages within our docker images #491
- [x] Update debian package creation with linux kernel model dependencies for WG #492
- [x] Write ansible scripts and deploy at least 3 nodes with WG support #494
- [x] Update WG related documentation. Running WG provider on Linux as docker / deb package
- [x] Create e2e test for WG transport green path. #614
