### ISSUE TITLE
Final removal of "openvpn" wording

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#530]
Opening this as a separate issue so we can spread it over a few PR's.

Leftovers:
- [x] TODO Decouple stats.Sender from 'openvpn' states #542 
- [x] TODO Move stats.Sender from 'openvpn' package #542
- [x] TODO Register Openvpn flags as transport "openvpn" arguments #499
- [ ] TODO Bootstrap services in desktop entrypoint only
- [ ] TODO Bootstrap openvpn together with transport
- [ ] TODO Use transport mock in tests instead of real openvpn
- [x] Move `mysteriumnetwork/go-openvpn/openvpn/core` to node repo #529
