### ISSUE TITLE
Feature/basic value transfer to provider with details

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#706]
- [x] [Fix the uint/int mess in session_payments.go](https://github.com/mysteriumnetwork/node/issues/707)
- [x] [Promise storage](https://github.com/mysteriumnetwork/node/issues/715)
- [x] [Initial promise state](https://github.com/mysteriumnetwork/node/issues/714)
- [x] [Consumer-side balance tracking](https://github.com/mysteriumnetwork/node/issues/717)
- [ ] Send signature along with initial promise info to consumer #750 
- [ ] [Send beneficiary address to the consumer](https://github.com/mysteriumnetwork/node/issues/718)
- [x] [Adjust provider/consumer balance after receiving/sending a promise](https://github.com/mysteriumnetwork/node/issues/716)
- [ ] [Payment alignment mechanism](https://github.com/mysteriumnetwork/node/issues/709)
- [ ] [Remove hardcoded params from providerBalanceTrackerFactory](https://github.com/mysteriumnetwork/node/issues/710)
- [ ] [Validate issuerID on provider side](https://github.com/mysteriumnetwork/node/issues/711)
- [ ] [Pass payment info to providerBalanceTrackerFactory](https://github.com/mysteriumnetwork/node/issues/712)
- [ ] [Ask for a new promise on the provider side](https://github.com/mysteriumnetwork/node/issues/713)
- [ ] [Promise clearing](https://github.com/mysteriumnetwork/node/issues/719)
- [ ] [Remove old promise package](https://github.com/mysteriumnetwork/node/issues/708)
- [ ] [Re-evaluate session creation dialog](https://github.com/mysteriumnetwork/node/issues/720)
- [ ] [Move relevant DTO from openvpn/discovery/dto](https://github.com/mysteriumnetwork/node/issues/761)
- [ ] [Minimal charge sum](https://github.com/mysteriumnetwork/node/issues/723)
- [ ] [Balance difference threshold percentage](https://github.com/mysteriumnetwork/node/issues/812)

**Comment by zolia** [comment]
outdated by new payment model
