### ISSUE TITLE
MYST ID registration for bounty program

### ISSUE THREAD

**Issue by AndriusMyst** [mysteriumnetwork/node#793]
**User Story:**
As a desktop VPN provider/consumer, 
I want to register MYST ID with real MYST
So that I can participate in the testing bounty program

**Requirements for dVPN & payments**
https://docs.google.com/presentation/d/1EHQIlXATgQ2dpQ5RUeKn-hS5kW9JLQJS8dtEG2opo9M/edit#slide=id.g501dca8d39_0_116

**Tasks:**
- [ ] Payments hi-lvl solution architecture - #796 @zolia 
- [ ] Deploy SC - #797 @chompomonim 
- [ ] Update E2E tests #798 - @tadovas 
- [ ] Update web wallet with new SC #799 - @chompomonim 
- [ ] Update desktop app to support new SC #800 - @Waldz 
- [ ] Go bindings for new SC #801 - @tadovas 

Staking question.
