### ISSUE TITLE
0.6 release todo list

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#810]
Yet to finish / enable :
 - [x] introduce --experimental-payments with 0 cost enabled by default
 - [x] introduce --experimental-natpunching disabled by default
 - [x] introduce working WG for Windows
 - [x] /service-sessions endpoint for tequilapi
