### ISSUE TITLE
0.7 release todo list

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#835]
**Implement whitelist:**
- [x] Implement whitelist "Mysterium verified identities" https://github.com/mysteriumnetwork/mysterium-vpn/issues/456

**IP categorisation:**
- [x] Implement LocationOracle for IP attributes detection @vkuznecovas 
 https://github.com/mysteriumnetwork/location-oracle/issues/2
- [x] Node integration with LocationOracle https://github.com/mysteriumnetwork/node/issues/863
- [x] Node autodetects IP attributes of Proposal https://github.com/mysteriumnetwork/node/issues/862
- [x] Discovery filters by IP attributes https://github.com/mysteriumnetwork/api/issues/107
- [x] Visualise IP attributes in Dashboard https://github.com/mysteriumnetwork/api/issues/108
- [x] dVPN app show IP attributes (country and type) before starting service https://github.com/mysteriumnetwork/mysterium-vpn/issues/466
- [x] Find DB or alternative solution to identify if it is a residential IP (https://github.com/mysteriumnetwork/location-oracle/issues/2)

**NAT traversal:**
- [ ] Implement NAT hole punching for WG
- [x] Present users with NAT traversal issues and possible solutions

**Testing:**
- [ ] Analyse information from beta testers to solve node running issues on Windows

**CI:**
- [ ] Optimise travis CI performance 

**Monitoring:**
- [x] Streaming monitoring analysis
