### ISSUE TITLE
[Dual node] - Week 14/15 TODO

### ISSUE THREAD

**Issue by ignasbernotas** [mysteriumnetwork/node#966]
- [x] Solve bugs to have stable app on Win 10
- [x] NAT manual configuration instructions: @zolia (https://github.com/mysteriumnetwork/docs/issues/22)
- [x] New app structure: @tadaskay (https://github.com/mysteriumnetwork/mysterium-vpn/issues/486)
- [x] As a user I'm able to select whitelist/all traffic before starting the node (https://github.com/mysteriumnetwork/mysterium-vpn/issues/456) (https://github.com/mysteriumnetwork/node/issues/838)
- [x] Contract review (https://github.com/mysteriumnetwork/operations/issues/251)
- [x] Error message with NAT instructions link when NAT fails: @zolia (https://github.com/mysteriumnetwork/node/issues/794)
- [x] As a user I see my IP and if it is residential/datacenter before starting a node (https://github.com/mysteriumnetwork/mysterium-vpn/issues/466)
- [ ] Tequilapi websockets (https://github.com/mysteriumnetwork/node/issues/735)
- [x] dVPN desktop new design slicing (https://github.com/mysteriumnetwork/mysterium-desktop/issues/1)
